Vagrant.require_version ">= 1.8.0", "< 1.9.0"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
    v.gui = false
  end
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.hostname = "student"

end
