
Vagrant.require_version ">= 1.7.0", "< 1.9.0"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.gui = false
    v.name = "compsci220-student-vm"
  end
  config.vm.provision :shell, inline: File.read("bootstrap.sh")

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.hostname = "student"

end
